# 数组方法

In [1]:
%pylab

Using matplotlib backend: <object object at 0x7fe0ef778440>
Populating the interactive namespace from numpy and matplotlib


## 求和

In [5]:
a = array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
sum(a)

21

In [4]:
sum(a,axis=0) # 沿第1维求和，纵向，整列求和

array([5, 7, 9])

In [7]:
sum(a,axis=1) # 沿第2维求和，横向，整行求和

array([ 6, 15])

In [8]:
sum(a,axis=-1) # 沿最后一维求和

array([ 6, 15])

In [9]:
a.sum()

21

In [10]:
a.sum(axis=0)

array([5, 7, 9])

In [11]:
a.sum(axis=1)

array([ 6, 15])

## 求积

In [12]:
a.prod()

720

In [15]:
prod(a,axis=0)

array([ 4, 10, 18])

## 求最大最小值

In [16]:
from numpy.random import rand
a = rand(3,4)
%precision 3
a

array([[0.884, 0.039, 0.79 , 0.518],
       [0.901, 0.02 , 0.991, 0.798],
       [0.73 , 0.371, 0.867, 0.942]])

In [17]:
a.min() # 全局最小值

0.02045034746305041

In [18]:
a.min(axis=0)

array([0.73 , 0.02 , 0.79 , 0.518])

In [19]:
a.max()

0.9913519095765356

In [20]:
a.max(axis=1)

array([0.884, 0.991, 0.942])

## 最大最小值的位置

In [21]:
a.argmin()

5

In [22]:
a.argmin(axis=0)

array([2, 1, 0, 0])

## 均值

In [26]:
a = array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
a.mean()

3.5

In [25]:
a.mean(axis=-1)

array([2., 5.])

In [27]:
mean(a)

3.5

In [28]:
average(a,axis=0)

array([2.5, 3.5, 4.5])

In [40]:
average(a,axis=0,weights=[2,1]) # 加权平均，avg = sum(a * weights) / sum(weights)

array([2., 3., 4.])

In [35]:
average(a,axis=1)

array([2., 5.])

In [41]:
average(a,axis=1,weights=[1,5,7]) # (1+2*2+3*3)/(1+5+7)=2.462

array([2.462, 5.462])

## 标准差，方差

In [42]:
a.std(axis=1) # 所有数减去其平均值的平方和，再除以数值个数，再把结果开根号

array([0.816, 0.816])

In [43]:
a.var(axis=1)

array([0.667, 0.667])

In [44]:
std(a,axis=1)

array([0.816, 0.816])

In [45]:
var(a,axis=1) # 所有数减去其平均值的平方和，再除以数值个数

array([0.667, 0.667])

## clip方法

In [46]:
a

array([[1, 2, 3],
       [4, 5, 6]])

将数值限制再某个范围内。小于3的变为3，大于5的变为5

In [47]:
a.clip(3,5)

array([[3, 3, 3],
       [4, 5, 5]])

## ptp方法

计算最大值和最小值之差

In [48]:
a.ptp(axis=1)

array([2, 2])

In [49]:
a.ptp()

5

## round方法

近似，默认近似到整数

In [50]:
a = array([1.35,2.5,1.5])

In [51]:
a.round()

array([1., 2., 2.])

In [53]:
a.round(decimals=1)

array([1.4, 2.5, 1.5])