# 数组类型

In [1]:
from numpy import *

## 复数数组

In [5]:
a = array([1+1j,2,3,4])
a

array([1.+1.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [6]:
a.dtype

dtype('complex128')

In [7]:
a.real

array([1., 2., 3., 4.])

In [8]:
a.imag

array([1., 0., 0., 0.])

In [10]:
a.imag = [1,2,3,4]
a

array([1.+1.j, 2.+2.j, 3.+3.j, 4.+4.j])

In [12]:
a.conj()

array([1.-1.j, 2.-2.j, 3.-3.j, 4.-4.j])

---
这些属性方法可以用在浮点数或者整数数组上：

In [13]:
a = array([0.,1,2,3])
a.dtype

dtype('float64')

In [14]:
a.real

array([0., 1., 2., 3.])

In [15]:
a.imag

array([0., 0., 0., 0.])

In [17]:
a.conj()

array([0., 1., 2., 3.])

但在这里，虚部是只读的，不能修改它的值

In [18]:
a.imag = [1,2,3,4]

TypeError: array does not have imaginary part to set

---

## 指定数组类型

In [19]:
a = array([0,1.,2,3])

In [20]:
a.dtype

dtype('float64')

In [22]:
a.nbytes # 8bytes*4

32

---
指定类型

In [23]:
a = array([0,1.,2,3],dtype=float32)

In [24]:
a.dtype

dtype('float32')

In [25]:
a.nbytes # 4bytes*4

16

---
指定有无符号

In [30]:
a = array([0,1,2,3],dtype=uint8) # 无符号整数
a.dtype

dtype('uint8')

In [31]:
a.nbytes # uint8只使用一个字节，表示0-255的整数

4

In [32]:
a = array([102,111,212],dtype=uint8)
a.tofile('foo.dat')

In [35]:
b = frombuffer('foo',dtype=uint8) # 报错
b

TypeError: a bytes-like object is required, not 'str'

In [36]:
import os
os.remove('foo.dat')

---

In [38]:
print(ord('f'))
print(ord('S'))

102
83


## Numpy类型

具体如下：

|基本类型|可用的**Numpy**类型|备注
|--|--|--
|布尔型|`bool`|占1个字节
|整型|`int8, int16, int32, int64, int128, int`| `int` 跟**C**语言中的 `long` 一样大
|无符号整型|`uint8, uint16, uint32, uint64, uint128, uint`| `uint` 跟**C**语言中的 `unsigned long` 一样大
|浮点数| `float16, float32, float64, float, longfloat`|默认为双精度 `float64` ，`longfloat` 精度大小与系统有关
|复数| `complex64, complex128, complex, longcomplex`| 默认为 `complex128` ，即实部虚部都为双精度
|字符串| `string, unicode` | 可以使用 `dtype=S4` 表示一个4字节字符串的数组
|对象| `object` |数组中可以使用任意值|
|Records| `void` ||
|时间| `datetime64, timedelta64` ||

任意类型的数组：

In [39]:
a = array([1,1.2,'hello',[10,20,30]],dtype=object)

In [40]:
a*2

array([2, 2.4, 'hellohello', list([10, 20, 30, 10, 20, 30])], dtype=object)

## 类型转换

In [41]:
a = array([1.5,-3],dtype=float32)
a

array([ 1.5, -3. ], dtype=float32)

### asarray方法

In [42]:
asarray(a,dtype=float64)

array([ 1.5, -3. ])

In [43]:
asarray(a,dtype=uint8)

array([  1, 253], dtype=uint8)

asarray不会修改原数组的值

In [44]:
a

array([ 1.5, -3. ], dtype=float32)

In [45]:
b = asarray(a,dtype=float32)

In [46]:
b is a # b和a指向同一块内存

True

这么做的好处在于，asarray不仅可以作用于数组，还可以将其他类型转化为数组。\
有些时候为了保证我们的输入值是数组，需要将其使用asarray转化，当它本来就是数组时，并不会产生新的对象，这就保证了效率。

In [47]:
asarray([1,2,3,4])

array([1, 2, 3, 4])

### astype方法

In [48]:
a.astype(float64)

array([ 1.5, -3. ])

In [49]:
a.astype(uint8)

array([  1, 253], dtype=uint8)

astype也不会改变原数组的值

In [50]:
a

array([ 1.5, -3. ], dtype=float32)

astype总是返回原来数组的一份复制，即使转换的类型是相同的

In [51]:
b = a.astype(float32)
print(a)
print(b)

[ 1.5 -3. ]
[ 1.5 -3. ]


In [52]:
b is a # b和a指向两块不同的内存

False

### view方法

In [54]:
a = array([1,2,3,4],dtype=int32)
a

array([1, 2, 3, 4], dtype=int32)

view会将a在内存中的表示看成是uint8进行解析

In [55]:
b = a.view(uint8)
b

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0], dtype=uint8)

In [57]:
a[0] = 2**30
a

array([1073741824,          2,          3,          4], dtype=int32)

修改a会更改b的值，因为a和b共用一块内存

In [58]:
b

array([ 0,  0,  0, 64,  2,  0,  0,  0,  3,  0,  0,  0,  4,  0,  0,  0],
      dtype=uint8)