# 数组形状

In [1]:
%pylab

Using matplotlib backend: <object object at 0x7fc60da19450>
Populating the interactive namespace from numpy and matplotlib


## 修改数组的形状

In [2]:
a = arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
a.shape = 2,3 # 修改原数组的值
a

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
a.reshape(3,2) # 返回一个新的值

array([[0, 1],
       [2, 3],
       [4, 5]])

In [7]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
a.reshape(4,2)

ValueError: cannot reshape array of size 6 into shape (4,2)

## 使用newaxis增加数组维数

In [10]:
a = arange(3)
shape(a)

(3,)

In [11]:
y = a[newaxis,:] # 在原维度 前 插入一个新维度
shape(y)

(1, 3)

In [13]:
y = a[:,newaxis] # 在原维度 后 插入一个新维度
shape(y)

(3, 1)

In [14]:
y = a[newaxis,newaxis,:] # 在原维度 前 插入两个新维度
shape(y)

(1, 1, 3)

## squeeze方法去除多余的轴

In [16]:
a = arange(6)
a.shape = 2,1,3

squeeze返回一个将所有长度为1的维度去除的新数组。

In [17]:
b = a.squeeze()
b.shape

(2, 3)

## 数组转置

In [18]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [19]:
a.transpose()

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

In [20]:
a.T # 缩写属性

array([[[0, 3]],

       [[1, 4]],

       [[2, 5]]])

注意：
- 对于复数数组，转置并不返回复共轭，只是单纯的交换轴的位置。
- 转置可以作用于多维数组。

In [25]:
a = arange(60)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [27]:
a.shape = 3,4,5
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [29]:
b = a.T
b.shape

(5, 4, 3)

转置只是交换了轴的位置，而且转置会改变原数组的值。

In [31]:
a = arange(6)
a.shape = 2,3
a

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
b  = a.T

In [37]:
b[0,1] = 30

In [38]:
a

array([[ 0,  1,  2],
       [30,  4,  5]])

## 数组连接

In [41]:
x = array([[0,1,2],[10,11,12]])
y = array([[50,51,52],[60,61,62]])
print(x.shape)
print(y.shape)

(2, 3)
(2, 3)


In [42]:
z = concatenate((x,y)) # 第0维
z

array([[ 0,  1,  2],
       [10, 11, 12],
       [50, 51, 52],
       [60, 61, 62]])

In [43]:
z.shape

(4, 3)

In [45]:
z = concatenate((x,y),axis=1) # 第1维
z

array([[ 0,  1,  2, 50, 51, 52],
       [10, 11, 12, 60, 61, 62]])

In [46]:
z.shape

(2, 6)

x和y的形状是一样的，还可以将它们连接成3维数组，但是concatenate不提供这样的功能，不过可以这样：

In [48]:
z = array((x,y))
z

array([[[ 0,  1,  2],
        [10, 11, 12]],

       [[50, 51, 52],
        [60, 61, 62]]])

In [49]:
z.shape

(2, 2, 3)

实际上，Numpy提供那个了分别对应这三种情况的函数：

In [50]:
vstack((x,y)).shape

(4, 3)

In [51]:
hstack((x,y)).shape

(2, 6)

In [56]:
dstack((x,y)).shape

(2, 3, 2)

## Flatten数组

flatten方法的作用是将多维数组转化为1维数组：

In [70]:
a = array([[0,1],[2,3]])
b = a.flatten()
b

array([0, 1, 2, 3])

返回的是数组的复制，因此改变b并不会影响a的值

In [71]:
b[0] = 10
print(a)
print(b)

[[0 1]
 [2 3]]
[10  1  2  3]


## flat属性

In [73]:
a.flat

a.flat相当于返回了所有元组组成的一个迭代器。

In [74]:
b = a.flat

In [75]:
b[0]

0

此时修改ｂ的值会影响ａ

In [76]:
b[0] = 10
print(a)

[[10  1]
 [ 2  3]]


In [77]:
a.flat[:]

array([10,  1,  2,  3])

## ravel方法

In [78]:
a = array([[0,1],[2,3]])
b = a.ravel()
b

array([0, 1, 2, 3])

修改b会改变a的值

In [79]:
b[0] = 10
a

array([[10,  1],
       [ 2,  3]])

但在另一种情况下

In [80]:
a = array([[0,1],[2,3]])
aa = a.transpose()
b = aa.ravel()
b

array([0, 2, 1, 3])

In [81]:
b[0] = 10

In [82]:
aa

array([[0, 2],
       [1, 3]])

In [83]:
a

array([[0, 1],
       [2, 3]])

可以看到，在这种情况下，修改b并不会改变aa的值，原因是我们用来ravel的对象aa本身是a的一个view。

## atleast_xd函数

atleast_xd函数，x可以取值1，2，3。

In [84]:
x = 1
atleast_1d(x)

array([1])

In [86]:
a = array([1,2,3])
b = atleast_2d(a)
b.shape

(1, 3)

In [87]:
b

array([[1, 2, 3]])

In [89]:
c = atleast_3d(b)

In [90]:
c.shape

(1, 3, 1)

In [91]:
c

array([[[1],
        [2],
        [3]]])

在scipy库中，这些函数被用来保证输入满足一定的条件：
|用法|scipy中出现次数|
|---|---|
|value.flaten() <br> value.flat <br> value.ravel()|~2000次|
|atleast_1d(value) <br> atleast_2d(value)|~700次|
|asarray(value)|~4000次|