# 数组排序

In [1]:
%pylab

Using matplotlib backend: <object object at 0x7fdfb506c450>
Populating the interactive namespace from numpy and matplotlib


## sort函数

In [2]:
names = array(['bob','sue','jan','ad'])
weights = array([20.8,93.2,53.4,61.8])
sort(weights)

array([20.8, 53.4, 61.8, 93.2])

## argsort函数

In [3]:
ordered_indices = argsort(weights)
ordered_indices

array([0, 2, 3, 1])

In [4]:
weights[ordered_indices]

array([20.8, 53.4, 61.8, 93.2])

In [5]:
names[ordered_indices]

array(['bob', 'jan', 'ad', 'sue'], dtype='<U3')

In [6]:
weights # 原值不改变

array([20.8, 93.2, 53.4, 61.8])

## sort和argsort方法

In [7]:
data = array([20.8,93.2,53.4,61.8])
data.argsort()

array([0, 2, 3, 1])

In [8]:
data

array([20.8, 93.2, 53.4, 61.8])

argsort方法和argsort函数没什么区别，也不会改变数组的值。但是sort方法会改变数组的值。

In [9]:
data.sort()

In [10]:
data

array([20.8, 53.4, 61.8, 93.2])

## 二维数组排序

对于多维数组，sort方法默认沿着最后一维开始排序。

In [19]:
a = array([[.2,.9,.5],[.4,.8,.3],[.9,.1,.7]])
a

array([[0.2, 0.9, 0.5],
       [0.4, 0.8, 0.3],
       [0.9, 0.1, 0.7]])

In [20]:
sort(a)

array([[0.2, 0.5, 0.9],
       [0.3, 0.4, 0.8],
       [0.1, 0.7, 0.9]])

In [21]:
sort(a,axis=0)

array([[0.2, 0.1, 0.3],
       [0.4, 0.8, 0.5],
       [0.9, 0.9, 0.7]])

## searchsorted函数

searchsorted接收两个参数，第一个参数必须是已排序的数组。

In [23]:
sorted_array = linspace(0,1,5)
values = array([.1,.8,.3,.12,.5,.25])

In [24]:
searchsorted(sorted_array,values)

array([1, 4, 2, 1, 2, 1])

已排序数组：
|0|1|2|3|4|
|---|---|---|---|---|
|0.0|0.25|0.5|0.75|1.0|

数值：
|值|0.1|0.8|0.3|0.12|0.5|0.25|
|---|---|---|---|---|---|---|
|插入的位置|1|4|2|1|2|1|

searchsorted返回的值相当于保持第一个已排序数组的排序性质不变，将第二个数组中的值插入第一个数组中的位置。\
例如0.1在[0.0,0.25)之间，所以插入时应当放在第一个数组的索引1处，故第一个返回值为1。0.8在[0.75,1)之间，应该插入到索引4处，返回值为4。

In [32]:
from numpy.random import rand
data = rand(100)
data.sort()
data

array([0.00396254, 0.00418145, 0.00642876, 0.01547547, 0.01896098,
       0.03463824, 0.04201433, 0.06143158, 0.0618612 , 0.06730142,
       0.07162199, 0.09252206, 0.13525299, 0.14743984, 0.15387124,
       0.16970741, 0.18096102, 0.18267382, 0.19064362, 0.19291908,
       0.22115554, 0.22242407, 0.22557832, 0.24451814, 0.26233523,
       0.27816866, 0.28412039, 0.29543102, 0.30155684, 0.30156197,
       0.31866658, 0.31950282, 0.32703552, 0.33304478, 0.33493743,
       0.35681071, 0.35857264, 0.37107571, 0.37788197, 0.3934908 ,
       0.41122796, 0.41479871, 0.4244008 , 0.43927913, 0.45981088,
       0.47314678, 0.47804788, 0.49762758, 0.49799217, 0.51581739,
       0.51829203, 0.51916705, 0.53759384, 0.54165502, 0.57631899,
       0.58192017, 0.60775372, 0.62110031, 0.63215503, 0.64743353,
       0.65212825, 0.65402209, 0.656202  , 0.6674789 , 0.6723371 ,
       0.67983324, 0.68463319, 0.69612967, 0.69733891, 0.73969081,
       0.73973141, 0.74532771, 0.74922072, 0.75856772, 0.77209

In [33]:
bounds = .4,.6 # 不加括号默认是元组。
bounds

(0.4, 0.6)

In [35]:
searchsorted(data,bounds)

array([40, 56])

In [27]:
low_idx,high_indx = searchsorted(data,bounds)

In [28]:
data[low_idx:high_indx] # 索引值在40-56之间的对应元素值，或者说是0.4-0.6之间的值

array([0.41410646, 0.4315108 , 0.43413592, 0.43693485, 0.43794136,
       0.44401401, 0.4460299 , 0.44747381, 0.45061309, 0.45911391,
       0.46514117, 0.47074297, 0.48166101, 0.49026264, 0.51386808,
       0.51723726, 0.53108669, 0.54765049, 0.55580354, 0.57252293,
       0.58219751, 0.58228214, 0.58265779, 0.58273938])