# 数组与字符串的转换

## tostring方法

In [1]:
import numpy as np

In [4]:
a = np.array([[1,2],[3,4]],dtype=np.uint8)
a

array([[1, 2],
       [3, 4]], dtype=uint8)

In [3]:
a.tostring()

b'\x01\x02\x03\x04'

这里使用了Fortran的格式，按照列来读数据。

## fromstring方法

使用fromstring函数从字符串中读取数据，不过要指定类型。

In [6]:
s = a.tostring()
a = np.fromstring(s,dtype=np.uint8)
a

<ipython-input-6-2da07e42d2b5>:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  a = np.fromstring(s,dtype=np.uint8)


array([1, 2, 3, 4], dtype=uint8)

In [7]:
a.shape = 2,2
a

array([[1, 2],
       [3, 4]], dtype=uint8)

对于文本文件，推荐使用
- loadtxt
- genfromtxt
- savetxt

对于二进制文本文件，推荐使用
- save
- load
- savez