# 一般函数

In [1]:
import numpy as np

## 三角函数

    sin(x)
    cos(x)
    tan(x)
    sinh(x)
    conh(x)
    tanh(x)
    arccos(x)
    arctan(x)
    arcsin(x)
    arccosh(x)
    arctanh(x)
    arcsinh(x)
    arctan2(x,y)
`arctan2(x,y)`返回`arctan(x/y)`

## 向量操作

In [67]:
x = np.array([[1,10],[2,12]])
y = np.array([[3,30],[4,14]])
# x = np.mat(x)
# y = np.mat(y)
x,y

(array([[ 1, 10],
        [ 2, 12]]),
 array([[ 3, 30],
        [ 4, 14]]))

In [68]:
np.dot(x,y) # 两个数组的点积

array([[ 43, 170],
       [ 54, 228]])

In [73]:
np.inner(x,y) # inner是第一个向量乘以第二个向量的转置

array([[303, 144],
       [366, 176]])

In [70]:
np.dot(x,y.T)

array([[303, 144],
       [366, 176]])

In [71]:
np.cross(x,y) # 对应行交叉相乘再相减

array([  0, -20])

In [72]:
np.vdot(y,x) # 两个向量的点积

479

In [74]:
np.outer(x,y) # 第一个向量的元素依次乘以第二个向量的元素

array([[  3,  30,   4,  14],
       [ 30, 300,  40, 140],
       [  6,  60,   8,  28],
       [ 36, 360,  48, 168]])

In [75]:
np.kron(x,y) # 对应行元素依次相乘

array([[  3,  30,  30, 300],
       [  4,  14,  40, 140],
       [  6,  60,  36, 360],
       [  8,  28,  48, 168]])

In [76]:
np.tensordot(x,y)

array(479)

## 其他操作

exp(x), log(x), log10(x), sqrt(x), absolute(x)\
conjugate(x), negtaive(x), ceil(x), floor(x), fabs(x), hypot(x), fmod(x), maximum(x,y), minimum(x,y)

In [81]:
x = np.array([1,2,3]) # 返回坐标点到原点的距离
y = np.array([4,5,6])
np.hypot(x,y)

array([4.12310563, 5.38516481, 6.70820393])

## 类型处理

    iscomplexobj
    iscomplex
    isrealobj
    isreal
    imag
    real
    real_if_close
    isscalar
    isneginf
    isposinf
    isinf
    isfinite
    isnan
    nan_to_num
    common_type
    typename

In [84]:
np.inf, -np.inf # 正负无穷

(inf, -inf)

In [85]:
np.nan # 非法值 not a number

nan

In [88]:
np.isinf(1.0), np.isinf(np.inf), np.isinf(-np.inf)

(False, True, True)

In [90]:
np.array([0]) / 0

<ipython-input-90-89167516e631>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0]) / 0


array([nan])

In [96]:
a = np.arange(5)  # 只有0/0会得到nan，非0值除以0会得到无穷大
b = a/0
b

<ipython-input-96-8903b18d4dbb>:2: RuntimeWarning: divide by zero encountered in true_divide
  b = a/0
<ipython-input-96-8903b18d4dbb>:2: RuntimeWarning: invalid value encountered in true_divide
  b = a/0


array([nan, inf, inf, inf, inf])

In [97]:
b == np.nan # nan与任何数比较都是nan

array([False, False, False, False, False])

In [98]:
np.isnan(b)

array([ True, False, False, False, False])

## 修改形状

    atleast_1d
    atleast_2d
    atleast_3d
    expand_dims
    apply_over_axes
    apply_along_axis
    hstack
    vstack
    dstack
    column_stack
    hsplit
    vsplit
    dsplit
    split
    squeeze

## 其他有用函数

    fix
    mod
    amax
    amin
    ptp
    sum
    cumsum
    prod
    cumprod
    diff
    angle

    unwrap
    sort_complex
    trim_zeros
    fliplr
    flipud
    rot90
    diag
    eye
    select
    extract
    insert

    roots
    poly
    any
    all
    disp
    unique
    nansum
    nanmax
    nanargmax
    nanargmin
    nanmin

`nan`开头的函数会进行相应的操作，但是忽略`nan`值