# 二元运算

In [1]:
import numpy as np

## 四则运算

|运算|函数|
|---|---|
|a + b|add(a,b)|
|a - b|substract(a,b)|
|a * b|mutiply(a,b)|
|a / b|divide(a,b)|
|a ** b|power(a,b)|
|a % b|remainder(a,b)|

In [2]:
a = np.array([1,2])
a * 3

array([3, 6])

In [3]:
a = np.array([1,2])
b = np.array([3,4])
a * b

array([3, 8])

In [4]:
np.multiply(a,b)

array([3, 8])

In [5]:
np.multiply(a,b,a) # 将返回值存入第三个参数

array([3, 8])

In [6]:
a

array([3, 8])

## 比较和逻辑运算

运算|函数<
--- | --- 
`==` | `equal`
`!=` | `not_equal`
`>` | `greater`
`>=` | `greater_equal`
`<` | `less`
`<=` | `less_equal`
| `logical_and`
| `logical_or`
| `logical_xor`
| `logical_not`
`&` | `bitwise_and`
 | `bitwise_or`
`^` | `bitwise_xor`
`~` | `invert`
`>>` | `right_shift`
`<<` | `left_shift`

等于操作是逐元素比较的：

In [7]:
a = np.array([[1,2,3,4],[2,3,4,5]])
b = np.array([[1,2,5,4],[1,3,4,5]])
a == b

array([[ True,  True, False,  True],
       [False,  True,  True,  True]])

所以，要比较两个数组是否一样时，不能直接使用`if a==b:`，而要使用`if all(a==b):`\
对于浮点数，由于存在精度问题，使用`allclose`会更好：`if allclose(a,b):`

`logical_and`也是逐元素的`and`操作

In [8]:
a = np.array([0,1,1])
b = np.array([0,10,0])
np.logical_and(a,b)

array([False,  True, False])

### 比特操作

In [9]:
a = np.array([1,2,4,8])
b = np.array([16,32,64,128])
a | b # 与

array([ 17,  34,  68, 136])

In [12]:
a = np.array([1,2,3,4], np.uint8)
~a # 取反

array([254, 253, 252, 251], dtype=uint8)

In [13]:
a << 3 # 左移

array([ 8, 16, 24, 32], dtype=uint8)

运算符&优先级大于比较运算如>等，必要时必须加上括号

In [14]:
a = np.array([1,2,4,8])
b = np.array([16,32,64,128])

(a > 3) & (b < 100)

array([False, False,  True, False])