# ufunc对象

Numpy有两种基本对象：ndarray(n-dimensional array object)和ufunc(universal function object)。ndarray是存储单一数据类型的多维数组，而ufunc则是能够对数组进行处理的函数。

例如，二元操作符对应的numpy函数，如add就是一种ufunc对象，他可以作用域数组中的每个元素

In [1]:
import numpy as np

In [5]:
a = np.array([2,1,2])
b = np.array([2,4,5])
np.add(a,b)

array([4, 5, 7])

查看支持的方法

In [7]:
dir(np.add)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

除此之外，大部分能够作用于数组的数学函数如三角函数等，都是ufunc对象

特别的，对于二元操作符对应的ufunc对象，支持以下方法

## reduce方法

    op.reduce(a)

将op沿某个轴应用，使得数组a的位数降低一维

add作用到一维数组上相当于求和：

$$
\begin{align}
y & = add.reduce(a) \\
& = a[0] + a[1] + ... + a[N-1] \\
& = \sum_{n=0}^{N-1} a[n]
\end{align}
$$

In [9]:
a = np.array([10,2,3,4])
np.add.reduce(a)

19

多维数组默认只按照第一维进行运算

In [11]:
a = np.array([[1,2,3],[4,5,6]])
np.add.reduce(a)

array([5, 7, 9])

指定维度

In [13]:
np.add.reduce(a,1)

array([ 6, 15])

作用于字符串

In [15]:
a = np.array(['ab','cd','ef'], object)
np.add.reduce(a)

'abcdef'

逻辑运算

In [16]:
a = np.array([1,1,0,1])
np.logical_and.reduce(a)

False

In [19]:
np.logical_or.reduce(a)

True

In [17]:
dir(np.logical_and)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

## accumulate方法

    op.accumulate(a)

accumulate可以看做保存reduce每一步的结果所形成的数组

$$
\begin{align}
y & = add.accumulate(a) \\
  & = \left[\sum_{n=0}^{0} a[n], \sum_{n=0}^{1} a[n], ..., \sum_{n=0}^{N-1} a[n] \right]
\end{align}
$$

与之前类似

In [20]:
a = np.array([1,2,3,4])
np.add.accumulate(a)

array([ 1,  3,  6, 10], dtype=int32)

In [21]:
a = np.array(['ab', 'cd', 'ef'], object)
np.add.accumulate(a)

array(['ab', 'abcd', 'abcdef'], dtype=object)

In [23]:
a = np.array([1,1,0,1])
np.logical_and.accumulate(a)

array([ True,  True, False, False])

In [24]:
np.logical_or.accumulate(a)

array([ True,  True,  True,  True])

## reduceat方法

    op.reduceat(a, indices)

reduceat方法将操作符运用到指定的下标上，返回一个与indices大小相同的数组：

$$
\begin{align}
y & = add.reduceat(a, indices) \\
  & = \left[\sum_{n=indice[0]}^{indice[1]-1} a[n], \sum_{n=indice[0]}^{indice[2]-1} a[n], ..., \sum_{n=indice[0]}^{indice[N]-1} a[n] \right]
\end{align}
$$

In [26]:
a = np.array([0,10,20,30,40,50])
indices = np.array([1,4])
np.add.reduceat(a, indices)

array([60, 90], dtype=int32)

这里，indices为[1,4]，所以60表示从下标1(包含)加到下标4(不包含)的结果，90表示从下标4(包含)加到末尾的结果

## outer方法

    op.outer(a,b)

对于 `a` 中每个元素，将op运用到他和b的每一个元素上所得到的的结果：

In [27]:
a = np.array([0,1])
b = np.array([1,2,3])

np.add.outer(a, b)

array([[1, 2, 3],
       [2, 3, 4]])

注意有顺序区别

In [29]:
np.add.outer(b, a)

array([[1, 2],
       [2, 3],
       [3, 4]])