# choose函数实现条件筛选

对于数组，我们有时候需要进行类似 switch 和 case 进行条件选择，此时使用 choose 函数十分方便

In [2]:
import numpy as np

In [3]:
control = np.array([[1,0,1], [2,1,0], [1,2,2]])
np.choose(control, [10,11,12])

array([[11, 10, 11],
       [12, 11, 10],
       [11, 12, 12]])

在上面的例子中，choose将0,1,2对应的值映射为10,11,12，这里的0,1,2表示对应的下标

事实上，choose不仅仅能接受下标参数，还可以接受下标所在的位置：

In [6]:
i0 = np.array([[0,5,2], [3,4,5], [6,7,8]])
i2 = np.array([[20,21,22], [23,24,25], [26,27,28]])
control = np.array([[1,0,1], [2,1,0], [1,2,2]])

np.choose(control, [i0, 12, i2])

array([[12,  5, 12],
       [23, 12,  5],
       [12, 27, 28]])

第一个12是control第一个1对应的[i0,12,i2]中的1，也就是12

第一个5是control第一个0对应的[i0,12,i2]中的i0的对应位置的值，也就是5

第一个23是control第一个2对应的[i0,12,i2]中的i2的对应位置的值，也就是23

下面的例子将数组中所有小于10的值变成了10

In [8]:
a = np.array([[0,1,2], [10,11,12], [20,21,22]])
a < 10

array([[ True,  True,  True],
       [False, False, False],
       [False, False, False]])

将所有小于10的数变为10

In [20]:
np.choose(a < 10, (a, 10))

array([[10, 10, 10],
       [10, 11, 12],
       [20, 21, 22]])

将小于10的值变为10，大于15的值变为15

In [21]:
a = np.array([[0,1,2], [10,11,12], [20,21,22]])
lt = a < 10
gt = a > 15

choice = lt + 2 * gt
choice

array([[1, 1, 1],
       [0, 0, 0],
       [2, 2, 2]])

In [22]:
np.choose(choice, (a, 10, 15))

array([[10, 10, 10],
       [10, 11, 12],
       [15, 15, 15]])