# 记录数组

记录数组(`record array`)与结构数组类似

In [7]:
import numpy as np

质点类型

In [8]:
partical_dtype = np.dtype([('mass', 'float'), ('velocity', 'float')])

生成记录数组要使用 `np.rec` 里的 `fromrecords` 方法

In [10]:
partical_rec = np.rec.fromrecords([(1,1), (1,2), (2,1), (1,3)], dtype=partical_dtype)
partical_rec

rec.array([(1., 1.), (1., 2.), (2., 1.), (1., 3.)],
          dtype=[('mass', '<f8'), ('velocity', '<f8')])

在记录数组中，域可以通过属性来获得

In [11]:
partical_rec.mass

array([1., 1., 2., 1.])

也可以通过域来查询

In [12]:
partical_rec['mass']

array([1., 1., 2., 1.])

但是记录数组的运行效率要比结构化数组慢一些

也可以通过将一个结构化数组看成记录数组

In [13]:
particals = np.array([(1,1), (1,2), (2,1), (1,3)], dtype=partical_dtype)

使用 `view` 方法看成 `recarray`

In [14]:
partical_rec = particals.view(np.recarray)

In [15]:
partical_rec.mass

array([1., 1., 2., 1.])

In [17]:
partical_rec.velocity

array([1., 2., 1., 3.])

对于自定义的类型，可以通过它的 `names` 属性查看它有哪些域

In [18]:
particals.dtype.names

('mass', 'velocity')